# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0
  pulumi: pulumi/pulumi@2.1.0
  slack: circleci/slack@4.12.6

jobs:
  provision:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - pulumi/login
      - node/install-packages:
          pkg-manager: yarn-berry
      - pulumi/update:
          working_directory: infrastructure
          stack: prod
          skip-preview: true
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-website

  pre-provision:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - pulumi/login
      - node/install-packages:
          pkg-manager: yarn-berry
      - pulumi/preview:
          working_directory: infrastructure
          stack: prod
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-website

  build:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Build hckr.studio website
          working_directory: hckr.studio
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .blendid
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
          channel: ntf-website

  deploy:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Deploy hckr.studio website
          working_directory: hckr.studio # change directory to deploy functions
          command: yarn wrangler pages deploy ../.blendid/public/hckr.studio --project-name hckr-studio
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
          channel: ntf-website
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          channel: ntf-website
workflows:
  ci:
    jobs:
      - provision:
          context:
            - pulumi
            - slack
          filters:
            branches:
              only: trunk
      - pre-provision:
          context:
            - pulumi
            - slack
          filters:
            branches:
              ignore: trunk
      - build:
          context:
            - slack
      - deploy:
          context:
            - cloudflare
            - slack
          requires:
            - build
            - provision
          filters:
            branches:
              only: trunk