# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0
  slack: circleci/slack@4.12.5

jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Build website
          command: yarn build
          working_directory: hckr.studio
      - run:
          name: Deploy website
          command: yarn wrangler pages deploy ../.blendid/public/hckr.studio --project-name hckr-studio
          working_directory: hckr.studio
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
          channel: ntf-website
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          channel: ntf-website

workflows:
  ci:
    jobs:
      - build:
          context:
            - cloudflare
            - slack
